/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLinkForm: typeof import('./src/components/AddLinkForm.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    AvatarButton: typeof import('./src/components/AvatarButton.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DeleteDialog: typeof import('./src/components/dialog/DeleteDialog.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    EditLinkDialog: typeof import('./src/components/dialog/EditLinkDialog.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LinkCard: typeof import('./src/components/LinkCard.vue')['default']
    LinkDataGrid: typeof import('./src/components/LinkDataGrid.vue')['default']
    LinkTable: typeof import('./src/components/LinkTable.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TopAppBar: typeof import('./src/components/TopAppBar.vue')['default']
  }
}
