/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLinkForm: typeof import('./src/components/AddLinkForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    EditButtons: typeof import('./src/components/EditButtons.vue')['default']
    FooterBar: typeof import('./src/components/FooterBar.vue')['default']
    LinkDataCard: typeof import('./src/components/LinkDataCard.vue')['default']
    LinkDataGrid: typeof import('./src/components/LinkDataGrid.vue')['default']
    PButton: typeof import('primevue/button')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopAppBar: typeof import('./src/components/TopAppBar.vue')['default']
  }
}
