version: '3'
services:
  magbox-frontend:
    hostname: magbox-frontend
    container_name: 'magbox-frontend'
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
      args:
        MODE: ${MODE}  # Pass MODE as a build argument
    ports:
      - '1001:1001'
    networks:
      - magbox-network

  magbox-backend:
    hostname: magbox-backend
    container_name: 'magbox-backend'
    image: 'magbox-backend:latest'
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - '9000:9000'
    networks:
      - magbox-network

networks:
  magbox-network:
    driver: bridge
