name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Wait for frontend to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build frontend Container'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: master
          check-name: 'Build Backend Container'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - name: executing remote ssh commands using keys
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            docker pull ghcr.io/timhi/magbox-backend:master
            docker pull ghcr.io/timhi/magbox-frontend:master
            docker compose up -d
