name: Deploy new containers

on:
  push:
    branches: [master]

permissions: read-all

jobs:
  publish:
    name: Deploy the new container
    runs-on: ubuntu-latest
    steps:
      - name: Wait for frontend to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: master
          check-name: frontend-container
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Wait for backend to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: master
          check-name: backend-container
          repo-token: ${{ secrets.PAT_WAIT }}
          wait-interval: 20

      - name: Pull container and restart compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            docker pull ghcr.io/timhi/magbox-backend:master
            docker pull ghcr.io/timhi/magbox-frontend:master
            docker compose up -d
