name: deploy new magbox container
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using keys
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            docker pull ghcr.io/timhi/magbox-backend:master
            docker pull ghcr.io/timhi/magbox-frontend:master
            docker compose up -d
