name: e2e Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          chmod +x docker/setup.sh
          ./docker/setup.sh

      - name: Run Playwright tests
        run: |
          docker run --rm \
            --name playwright-tests \
            --network docker_magbox-network \
            --env CI=true \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            --entrypoint npx \
            mcr.microsoft.com/playwright:v1.51.1-jammy \
            playwright test
