name: e2e Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Set up Docker
        run: |
          chmod +x docker/setup.sh
          cd docker
          ./setup.sh

      - name: Install dependencies
        run: |
          cd e2e
          npm ci

      - name: Run Playwright tests
        working-directory: ./e2e
        run: |
          docker run --rm \
            --name playwright-tests \
            --network docker_magbox-network \
            --env CI=true \
            -v "${{ github.workspace }}/e2e:/workspace" \
            -w /workspace \
            --entrypoint npx \
            mcr.microsoft.com/playwright:v1.51.1-jammy \
            playwright test
