name: Run tests and linting

on: [pull_request]

jobs:  
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              cd frontend/
              npm ci
              npm run build
              npm run test:unit
              npm run test:e2e
              npm run lint